---
name: ((deployment_name))

instance_groups:
- name: sentinel-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_master)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      bind: ((redis_sentinel_bind))
      password: ((redis_sentinel_password))
  - name: redis_sentinel_exporter
    release: ((release_name))
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_slave)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
  - name: redis_sentinel_exporter
    release: ((release_name))
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}

variables:
- name: redis_sentinel_password
  type: password
  parameters:
    length: ((password_length))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 3
  update_watch_time: 60000-120000
  serial: false
