---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: redis-service
  - name: redis
    release: redis-service
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
      sentinel_slave_conn: {from: ((shared_sentinel_slave)), deployment: ((shared_sentinel_deployment))}
    properties:
      bind: ((redis_bind))
      port: '0'
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      replication: true
      replica_password: ((redis_replica_password))
      sentinel_password: ((redis_sentinel_user_password))
      tls: true
      tls_dh_length: ((redis_dh_length))
      tls_replication: true
  - name: redis_check
    release: redis-service
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
      sentinel_slave_conn: {from: ((shared_sentinel_slave)), deployment: ((shared_sentinel_deployment))}
  - name: redis_exporter
    release: redis-service
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
    properties:
      skip_tls_verification: true
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk_type: ((default_persistent_disk_type))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: redis-service
  - name: redis_broker-1.5
    release: redis-service
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
      sentinel_slave_conn: nil
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls: true
  - name: redis_broker_check-1.5
    release: redis-service

variables:
- name: redis_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_admin_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_exporter_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_replica_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_sentinel_user_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_broker_password
  type: password
  parameters:
    length: ((password_length))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: redis-service
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 2
  update_watch_time: 60000-120000
  serial: false
