---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
      sentinel_slave_conn: {from: ((shared_sentinel_slave)), deployment: ((shared_sentinel_deployment))}
    properties:
      bind: ((redis_bind))
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      replica_password: ((redis_replica_password))
      sentinel_password: ((redis_sentinel_user_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      replication: ((redis_replication))
  - name: redis_check
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
      sentinel_slave_conn: {from: ((shared_sentinel_slave)), deployment: ((shared_sentinel_deployment))}
  - name: redis_exporter
    release: ((release_name))
    consumes:
      redis_sentinel_conn: nil
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_broker-1.5
    release: ((release_name))
    consumes:
      slave_conn: nil
      redis_sentinel_conn: {from: ((shared_sentinel_master)), deployment: ((shared_sentinel_deployment))}
      sentinel_slave_conn: {from: ((shared_sentinel_slave)), deployment: ((shared_sentinel_deployment))}
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls: ((redis_broker_tls))
  - name: redis_broker_check-1.5
    release: ((release_name))

variables:
- name: redis_password
  type: password
- name: redis_admin_password
  type: password
- name: redis_exporter_password
  type: password
- name: redis_replica_password
  type: password
- name: redis_sentinel_user_password
  type: password
- name: redis_broker_password
  type: password

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 3
  update_watch_time: 60000-120000
  serial: true
