---
name: ((deployment_name))

instance_groups:
- name: redis-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis
    release: ((release_name))
    provides:
      redis_conn: {as: master}
    consumes:
      redis_conn: {from: master}
      slave_conn: {from: slave}
    properties:
      bind: ((redis_bind))
      port: ((redis_port))
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      replica_password: ((redis_replica_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      cluster_enabled: ((redis_cluster_enabled))
      cluster_replicas_per_node: ((replicas_per_node_count))
      tls: ((redis_tls))
      tls_ca_certificate: ((redis_ca_certificate))
      tls_ca_private_key: ((redis_ca_private_key))
      tls_dh_length: ((redis_dh_length))
      tls_replication: ((redis_tls_replication))
      tls_cluster: ((redis_tls_cluster))
  - name: redis_check
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
      slave_conn: {from: slave}
  - name: redis_exporter
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
    properties:
      skip_tls_verification: ((redis_exporter_skip_tls_verification))
- name: redis-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis
    release: ((release_name))
    provides:
      redis_conn: {as: slave}
    consumes:
      redis_conn: {from: master}
      slave_conn: {from: slave}
    properties:
      tls_dh_length: ((redis_dh_length))
  - name: redis_check
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
      slave_conn: {from: slave}
  - name: redis_exporter
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
    properties:
      skip_tls_verification: ((redis_exporter_skip_tls_verification))
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_broker-1.5
    release: ((release_name))
    consumes:
      redis_conn: {from: master}
      slave_conn: {from: slave}
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls: ((redis_broker_tls))
  - name: redis_broker_check-1.5
    release: ((release_name))

variables:
- name: redis_password
  type: password
- name: redis_admin_password
  type: password
- name: redis_exporter_password
  type: password
- name: redis_replica_password
  type: password
- name: redis_broker_password
  type: password

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 8
  update_watch_time: 60000-120000
  serial: true
