---
name: ((deployment_name))

instance_groups:
- name: redis
  azs: [((default_az))]
  instances: ((node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: redis
    release: ((release_name))
    consumes:
      slave_conn: nil
    properties:
      bind: ((redis_bind))
      password: ((redis_password))
      admin_password: ((redis_admin_password))
      exporter_password: ((redis_exporter_password))
      replica_password: ((redis_replica_password))
      maxmemory: ((redis_maxmemory))
      maxmemory_policy: ((redis_maxmemory_policy))
      cluster_enabled: ((redis_cluster_enabled))
      cluster_replicas_per_node: ((replicas_per_node_count))
  - name: redis_check
    release: ((release_name))
    consumes:
      slave_conn: nil
  - name: redis_exporter
    release: ((release_name))
- name: broker
  azs: [((default_az))]
  instances: 1
  vm_type: ((default_vm_type))
  stemcell: default
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_broker-1.5
    release: ((release_name))
    consumes:
      slave_conn: nil
    properties:
      bind: ((redis_bind))
      password: ((redis_broker_password))
      tls: ((redis_broker_tls))
  - name: redis_broker_check-1.5
    release: ((release_name))

variables:
- name: redis_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_admin_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_exporter_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_replica_password
  type: password
  parameters:
    length: ((password_length))
- name: redis_broker_password
  type: password
  parameters:
    length: ((password_length))

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 8
  update_watch_time: 60000-120000
  serial: true
