---
name: ((deployment_name))

instance_groups:
- name: sentinel-master
  azs: [((default_az))]
  instances: ((master_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_master)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      bind: ((redis_sentinel_bind))
      port: ((redis_sentinel_port))
      password: ((redis_sentinel_password))
      tls: ((redis_sentinel_tls))
      tls_ca_certificate: ((sentinel_ca_certificate))
      tls_ca_private_key: ((sentinel_ca_private_key))
      tls_dh_length: ((redis_dh_length))
      tls_replication: ((redis_tls_replication))
- name: sentinel-slave
  azs: [((default_az))]
  instances: ((slave_node_count))
  vm_type: ((default_vm_type))
  stemcell: default
  persistent_disk: ((persistent_disk_size))
  networks:
  - name: ((default_network))
  jobs:
  - name: haveged
    release: ((release_name))
  - name: redis_sentinel
    release: ((release_name))
    provides:
      redis_sentinel_conn: {as: ((shared_sentinel_slave)), shared: true}
    consumes:
      redis_sentinel_conn: {from: ((shared_sentinel_master))}
    properties:
      tls_dh_length: ((redis_dh_length))

variables:
- name: redis_sentinel_password
  type: password

stemcells:
- alias: default
  os: ((stemcell_os))
  version: "((stemcell_version))"

releases:
- name: ((release_name))
  version: latest

update:
  canaries: 2
  canary_watch_time: 60000-120000
  max_in_flight: 3
  update_watch_time: 60000-120000
  serial: false
